### ISSUE TITLE
Änderung der Profil E-Mail

### ISSUE THREAD

**Issue by phips0** [fosterfarrell9/mampf#10]
In den Profil-Einstellung gibt es **keine möglichkeit** seine E-Mail Adresse zu ändern.

**Comment by flugdrachen** [comment]
Fände ich auch praktisch

**Comment by fosterfarrell9** [comment]
Morgen kommt ein frisches Major Release, da wird es diese Möglichkeit geben. (Aktuell geht es übrigens auch, allerdings ziemlich gut versteckt: Auf "Passwort ändern" gehen, dort die neue Email-Adresse eingeben und einmalig das alte Passwort.)

**Comment by fosterfarrell9** [comment]
Ist nun möglich.
