### ISSUE TITLE
Truncation für sehr lange Medienbeschreibungen in THymE

### ISSUE THREAD

**Issue by flugdrachen** [fosterfarrell9/mampf#11]
Wenn die Medienbeschreibungen zu lang sind, werden sie zwar mit "..." abgekürzt, aber nicht kurz genug, siehe Screenshot:

![screenshot 253](https://user-images.githubusercontent.com/24362439/52312180-ee8de800-29a9-11e9-910f-d571a99e8ec6.png)

Die Schrift verschwindet, wenn man mit dem Mauszeiger über dem obersten Feld (hier "Punktspiegelungen") hovert.

![screenshot 254](https://user-images.githubusercontent.com/24362439/52312181-ee8de800-29a9-11e9-8cdf-f655746db2fd.png)

**Comment by fosterfarrell9** [comment]
In der neuesten Fassung von MaMpf ist das behoben. Anstelle von Abkürzungen gibt es jetzt rechts eine Scrollbar.
