### ISSUE TITLE
Kaviar/Lektionen: Anzeigeoption "Alle" zeigt nicht alle Medien an.

### ISSUE THREAD

**Issue by haeberlem** [fosterfarrell9/mampf#12]
Klickt man im Kaviar/Lektionen auf "Alle" so werden lediglich die ersten (bzw. bei umgekehrter Reihenfolge die letzten) 25 Vorlesungen angezeigt und nicht alle vorhandenen Medien.

**Comment by fosterfarrell9** [comment]
Danke für den Hinweis, sehr aufmerksam! Ist in der neuesten Version gefixt.
