### ISSUE TITLE
Layoutfehler auf der mobilen Website

### ISSUE THREAD

**Issue by flugdrachen** [fosterfarrell9/mampf#13]
An machen Stellen auf der mobilen Version von MamPf sehen Dinge nicht sehr schön aus:

- Lange Tags werden nicht umgebrochen
![screenshot_20190207-175417](https://user-images.githubusercontent.com/24362439/53587444-a61db080-3b8a-11e9-9813-f77e0e1c16cd.png)

- Der "Alle Erledigen" Button für Benachrichtungen hängt komisch rum
![screenshot_20190207-174130](https://user-images.githubusercontent.com/24362439/53587522-e2511100-3b8a-11e9-961f-63c87ad28bed.png)
![screenshot_20190207-174136](https://user-images.githubusercontent.com/24362439/53587523-e2511100-3b8a-11e9-9b1f-6d3a25c0419b.png)

- Dropdown-Menüs, die sich zur Seite öffnen, passen bisweilen nicht auf den Bildschirm
![screenshot_20190207-225937](https://user-images.githubusercontent.com/24362439/53587564-03196680-3b8b-11e9-8c4d-d4f9150c2f1f.png)

**Comment by fosterfarrell9** [comment]
In der neuesten Fassung habe ich an diesen Punkten gearbeitet. Auf meinem Smartphone (Pixel XL 2) sind die Probleme damit behoben, vielleicht können Sie es ja mal auf Ihrem Smartphone probieren.

**Comment by flugdrachen** [comment]
Es sieht auch bei mir so aus, als ob alles behoben ist.
