### ISSUE TITLE
THymE - Vollbildmodus lässt sich nach Verlassen nicht wieder betreten

### ISSUE THREAD

**Issue by flugdrachen** [fosterfarrell9/mampf#14]
Wenn ich an meinem PC ein Video mit THymE anschaue, in den Vollbildmodus wechsle und ihn dann wieder verlasse, dann lässt er sich nicht wieder betreten, der entsprechende Button zeigt auch noch die "Vollbild-Verlassen"-Funktion: 
![grafik](https://user-images.githubusercontent.com/24362439/54062087-5bdca500-4204-11e9-980e-80e28a4061e7.png)

**Comment by fosterfarrell9** [comment]
Bin gerade im Urlaub und kann daher z.Zt. nichts machen. Ist aber interessant, denn zum Launch von THymE hatte ich genau diese Funktionalität sehr ausgiebig mit verschiedensten Browsern getestet. Vielleicht haben die Browserhersteller mal wieder an der Fullscreen-API herumgedoktert.
Interessant wäre für mich jetzt: Welcher Browser wurde verwendet? Welche Version? Zeigen andere Browser dasselbe Verhalten? Gibt es einen Unterschied, ob man den Vollbildmodus über Esc/F11 beendet oder über das Mampf-eigene „Vollbild verlassen“-Icon (oder die Taste „f“)?

**Comment by fosterfarrell9** [comment]
Ich habe einUpdate eingespielt, das das Problem beheben sollte. Bitte mal prüfen.

**Comment by flugdrachen** [comment]
Es funktioniert jetzt. 

Allerdings ist nach Öffnen und Wiederverlassen, egal ob mit Icon, Taste f oder F11, der Player etwas kleiner als davor und nimmt nicht mehr die gesamte Fensterhöhe ein (in Firefox 65.0.2).

Aber das ist ja höchstens ein kosmetischer Fehler :)

**Comment by fosterfarrell9** [comment]
Anscheinend triggered das fullscreenchange-Event zweimal(!) das resize-Event für das Fenster, und beim zweiten Mal liest jQuery - warum auch immer - eine falsche Fensterhöhe aus, so dass die vom resize-Event getriggerte ThymeContainer-Resize-Funktion den Thyme-Container falsch platziert. Es ist unklar, was hier genau für den Fehler verantwortlich ist. Ich habe das jetzt mal brute force fürs erste so behoben, dass mit etwas Zeitverzögerung nach Auslösen des fullscreenchange-Events ein weiteres Mal der Thyme-Container resized wird. Das sollte funktionieren, solange der Rechner nicht zu langsam ist (in dem Fall dauert der fullscreenchange-Vorgang zu lange und das erneute resizing kommt zu früh...). Testen Sie bitte mal, ob das bei Ihnen jetzt geht.

**Comment by flugdrachen** [comment]
Das resize funktioniert, wenn der Vollbildmodus mit Icon und Taste f betreten wurde (egal wie ich ihn verlasse), nach Betreten und Verlassen des Vollbildmodus mit F11 ist unten immer noch ein kleiner schwarzer Rand.
Wie mir jetzt beim ausprobieren aufgefallen ist, nimmt der Player auch im Vollbildmodus nicht die ganze Fensterhöhe ein:
Bei Icon und bei Taste f ist unten ein schwarzer Rand, bei F11 ein kleinerer oben und unten.

Außerdem finde ich es merkwürdig, dass ich, wenn ich mit F11 in den Vollbildmodus gewechselt bin, mit der Taste f und dem Icon nicht den Vollbildmodus verlassen kann, sondern erst in den "richtigen?" Vollbildmodus wechsle - der oben erwähnte schwarze Rand wechselt dann auch. 
Wenn ich hingegen mit Taste f oder Icon in den Vollbildmodus gewechselt bin, wird dieser auch verlassen, wenn ich F11 drücke.
Dieser Unterschied ist sehr unintuitiv.

**Comment by fosterfarrell9** [comment]
Das sehe ich auch so, leider kann ich im Moment nichts dagegen tun. Die Browser haben aktuell **zwei** Vollbildmodi:  Einen eingebauten "F11-Vollbildmodus", auf den ich keinen Zugriff habe (der u.a. keine Events triggert), und einen API-Vollbildmodus, den ich kontrollieren kann. Siehe die Antwort [hierzu](https://stackoverflow.com/questions/43392583/fullscreen-api-not-working-if-triggered-with-f11) . 
Deswegen wird das leider fürs erste so bleiben müssen (auf irgendwelche Hacks habe ich keine Lust, dafür ist mir das Problem dann doch zu unbedeutend).
