### ISSUE TITLE
Error beim Selbsttest

### ISSUE THREAD

**Issue by christian-heusel** [fosterfarrell9/mampf#40]
Ich habe aus Jux eben mal schauen wollen, wie viele Themen ich für einen Selbsttest auswählen kann: [Link](https://mampf.mathi.uni-heidelberg.de/courses/2/take_random_quiz?tag_ids%5B%5D=39&tag_ids%5B%5D=161&tag_ids%5B%5D=107&tag_ids%5B%5D=1101&tag_ids%5B%5D=1108&tag_ids%5B%5D=142&tag_ids%5B%5D=1100&tag_ids%5B%5D=1115&tag_ids%5B%5D=379&tag_ids%5B%5D=108&tag_ids%5B%5D=131&tag_ids%5B%5D=141&tag_ids%5B%5D=182&tag_ids%5B%5D=213&tag_ids%5B%5D=133&tag_ids%5B%5D=233&tag_ids%5B%5D=134&tag_ids%5B%5D=121&tag_ids%5B%5D=47&tag_ids%5B%5D=123&tag_ids%5B%5D=247&tag_ids%5B%5D=224&tag_ids%5B%5D=135&tag_ids%5B%5D=103&tag_ids%5B%5D=132&tag_ids%5B%5D=130&tag_ids%5B%5D=128&tag_ids%5B%5D=122&tag_ids%5B%5D=120&tag_ids%5B%5D=179&tag_ids%5B%5D=196&tag_ids%5B%5D=211&tag_ids%5B%5D=452&tag_ids%5B%5D=59&tag_ids%5B%5D=150&tag_ids%5B%5D=188&tag_ids%5B%5D=603&tag_ids%5B%5D=1107&tag_ids%5B%5D=240&tag_ids%5B%5D=186&tag_ids%5B%5D=1109&tag_ids%5B%5D=214&tag_ids%5B%5D=203&tag_ids%5B%5D=49&tag_ids%5B%5D=154&tag_ids%5B%5D=183&tag_ids%5B%5D=38&tag_ids%5B%5D=43&tag_ids%5B%5D=175&tag_ids%5B%5D=223&tag_ids%5B%5D=222&tag_ids%5B%5D=166&tag_ids%5B%5D=1093&tag_ids%5B%5D=173&tag_ids%5B%5D=1112&tag_ids%5B%5D=184&tag_ids%5B%5D=1094&tag_ids%5B%5D=237&tag_ids%5B%5D=243&tag_ids%5B%5D=602&tag_ids%5B%5D=45&tag_ids%5B%5D=232&tag_ids%5B%5D=1095&tag_ids%5B%5D=216&tag_ids%5B%5D=212&tag_ids%5B%5D=206&tag_ids%5B%5D=129&tag_ids%5B%5D=236&tag_ids%5B%5D=69&tag_ids%5B%5D=249&tag_ids%5B%5D=127&tag_ids%5B%5D=207&tag_ids%5B%5D=1104&tag_ids%5B%5D=218&tag_ids%5B%5D=1103&tag_ids%5B%5D=1099&tag_ids%5B%5D=137&tag_ids%5B%5D=1110&tag_ids%5B%5D=1106&tag_ids%5B%5D=1105&tag_ids%5B%5D=372&tag_ids%5B%5D=151&tag_ids%5B%5D=109&tag_ids%5B%5D=169&tag_ids%5B%5D=197&tag_ids%5B%5D=239&tag_ids%5B%5D=51&tag_ids%5B%5D=178&tag_ids%5B%5D=1620&tag_ids%5B%5D=712&tag_ids%5B%5D=158&tag_ids%5B%5D=244&tag_ids%5B%5D=152&tag_ids%5B%5D=153&tag_ids%5B%5D=601&tag_ids%5B%5D=1096&tag_ids%5B%5D=1098&tag_ids%5B%5D=48&tag_ids%5B%5D=250&tag_ids%5B%5D=155&tag_ids%5B%5D=180&tag_ids%5B%5D=185&tag_ids%5B%5D=248&tag_ids%5B%5D=453&tag_ids%5B%5D=171&tag_ids%5B%5D=172&tag_ids%5B%5D=126&tag_ids%5B%5D=238&tag_ids%5B%5D=1090&tag_ids%5B%5D=162&tag_ids%5B%5D=144&tag_ids%5B%5D=165&tag_ids%5B%5D=1113&tag_ids%5B%5D=149&tag_ids%5B%5D=170&tag_ids%5B%5D=599&tag_ids%5B%5D=1102&tag_ids%5B%5D=139&tag_ids%5B%5D=143&tag_ids%5B%5D=40&tag_ids%5B%5D=140&tag_ids%5B%5D=1088&tag_ids%5B%5D=1089&tag_ids%5B%5D=1087&tag_ids%5B%5D=215&tag_ids%5B%5D=136&tag_ids%5B%5D=357&tag_ids%5B%5D=1091&tag_ids%5B%5D=1092&tag_ids%5B%5D=167&tag_ids%5B%5D=228&tag_ids%5B%5D=209&tag_ids%5B%5D=231&tag_ids%5B%5D=1111&tag_ids%5B%5D=1114&tag_ids%5B%5D=181&count=5)

Die Antwort scheint zumindest mal zu sein: Nicht alle ... :smile: 

![image](https://user-images.githubusercontent.com/26827864/80582937-d6234680-8a0f-11ea-9f1d-fc0acacbdabf.png)

Jetzt könnte man sich vielleicht mal anschauen, wie viele es braucht um das zum Failen zu bringen und dann fixen oder zumindest eine transparentere Fehlermeldung schreiben ...

**Comment by fosterfarrell9** [comment]
Ha, raffiniert. Muss ich mal in development austesten. Aktuell gibt das halt eine `ActionDispatch::Cookies::CookieOverflow`-exception, die nicht abgefangen wird.

**Comment by fosterfarrell9** [comment]
Ist auf -dev gefixt. Bitte mal testen.

**Comment by christian-heusel** [comment]
Crasht bei mir auf den ersten Blick nicht mehr :)
