### ISSUE TITLE
E-Mail Benachrichtigungen

### ISSUE THREAD

**Issue by christian-heusel** [fosterfarrell9/mampf#41]
Ich finde die E-Mail Benachrichtigungen könnte man noch etwas ansprechender gestalten, im Moment sehen sie nämlich noch so aus: 

![image](https://user-images.githubusercontent.com/26827864/80751237-b8e29b00-8b29-11ea-88cf-8d8cba1a8eed.png)
Als Beispiel fände ich das hier etwas ansprechender, wurde mit dem `go` Paket [hermes](https://github.com/matcornic/hermes) erstellt, vielleicht existiert so was für RoR ja auch.
![image](https://user-images.githubusercontent.com/26827864/80752018-204d1a80-8b2b-11ea-9380-e876d9ecd064.png)

Man muss trotz fancy Darstellung dann aber ja immer noch darauf achten, dass die Plaintextdarstellung der Mail ausreichend ist, wie man das widerum macht weiß ich nicht.

**Comment by fosterfarrell9** [comment]
Dafür gibt es in Rails das [premailer](https://github.com/fphilipe/premailer-rails) gem. Sollte eigentlich recht simpel sein. Die Mails liegen in app/views/notification_mailer .

**Comment by christian-heusel** [comment]
I made some progress :package: 

![image](https://user-images.githubusercontent.com/26827864/88343368-88358a80-cd41-11ea-8618-63b4506ddc0b.png)

**Comment by christian-heusel** [comment]
I tried to modify the announcements in the same fashion in PR #59: 
![image](https://user-images.githubusercontent.com/26827864/91098269-79ecce00-e661-11ea-8162-c4e9660e8f9d.png)
