### ISSUE TITLE
Crash beim Anlegen eines neuen Tags

### ISSUE THREAD

**Issue by christian-heusel** [fosterfarrell9/mampf#44]
Das erstellen eines neuen Tags erzeugt die "klassische" Fehlermeldung.

https://mampf.mathi.uni-heidelberg.de/tags/new

![image](https://user-images.githubusercontent.com/26827864/80948573-af3f8880-8df2-11ea-8f81-37d029a41205.png)

**Comment by fosterfarrell9** [comment]
Ist auf -dev behoben. Bitte mal testen.

**Comment by christian-heusel** [comment]
Klappt auf mampf-dev bei mir auch
