### ISSUE TITLE
Zugang zu Vorlesungen über Zugangscode

### ISSUE THREAD

**Issue by erichhasl** [fosterfarrell9/mampf#45]
Manche Dozent*innen weichen auf Moodle aus, da MaMpf und damit auch Vorlesungsinhalte, etc. allen, auch Universitätsexternen, zugänglich ist.

Wäre es denkbar, entweder für die Registrierung im MaMpf eine Uni-ID vorrauszusetzen, möglicherweise unpraktisch für Erstis die noch keine Uni-ID haben, oder einzelne Vorlesungen optional mit einem Zugangscode auszustatten, sodass, wenn das von dem*der Dozent*in gewünscht ist, die Vorlesungsinhalte für Nicht-Hörer*innen zu verstecken?

**Comment by fosterfarrell9** [comment]
Das Feature, Vorlesungen mit einem Zugangscode zu versehen, gibt es bereits, es wird auch von einigen Vorlesungen benutzt. Versuchen, Sie mal, in MaMpf alles zu abonnieren, was es gibt, dann sehen Sie, welche ;-)
Ansonsten ist die freie Zugänglichkeit - wenn von den Dozierenden gewünscht - Teil der Philosophie von MaMpf: Ersties haben in der Tat häufig erst verspätet eine Uni-Id, SchülerInnen können auf MaMpf bei Interesse in die Unimathe hereinschnuppern, ReferendarInnen (und LehrerInnen) können Materialien weiterverwenden, die sie während des Studiums benutzt haben. Die Verfügbarkeit von Inhalten an ausbildungsabschnittsbezogene IDs zu koppeln, schafft  Diskontinuitäten, die der nachhaltigen Verwendung der Inhalte entgegenwirken.
