### ISSUE TITLE
THymE Titel

### ISSUE THREAD

**Issue by christian-heusel** [fosterfarrell9/mampf#60]
Im moment ist im Player der Titel einfach nur "THymE", ich finde aber, dass hier auch noch informationen über das jeweilige Medium angezeigt werden könnten, die folgenden Optionen hätte ich für "Lektion (V) Einführung in die Numerik, SS 2020, Sitzung 21, 07.07.2020 Trigonometrische Interpolation"

* 21 - Trigonometrische Interpolation
* Trigonometrische Interpolation
* THymE - Trigonometrische Interpolation

Was denkt ihr dazu?

**Comment by tynsh** [comment]
Bei den PDFs könnte man auch den richtigen Titel hinterlegen. Akutell wird beim Öffnen eines Skriptes nur eine lange Zeichenfolge angezeigt. Man könnte sich hierfür in die Funktionsweise von content disposition einlesen

**Comment by fosterfarrell9** [comment]
Es gibt jetzt einen Pull Request dazu #63 , zumindest für den Titel beim THyme Player. Wie das bei den pdfs funktionieren soll, ist mir unklar, da hier nur eine Weiterleitung auf den Link auf den Medienserver gemacht wird.
