### ISSUE TITLE
Empty locale cookie crashes rendering

### ISSUE THREAD

**Issue by henrixapp** [fosterfarrell9/mampf#74]
If you supply an empty locale cookie 🥠 (done by accident  while testing), the application renders an error and is unusable.

The culprit is here https://github.com/fosterfarrell9/mampf/blob/f117f860a277e6219183861605c0aadc17f4fb58/app/controllers/application_controller.rb#L80

This causes the `enforce_available_locales!` to crash, because the locale "" is unknown.

A possible way to mitigate this, would be:
```ruby
if cookies[:locale].in?(I18n.available_locales.map(&:to_s))
  cookie_param = cookies[:locale]
end
I18n.locale = current_user.try(:locale) || locale_param ||
                    cookie_param || I18n.default_locale
```

**Comment by henrixapp** [comment]
The locale was empty because the account was created by command. I added an validation, that validates empty and correct locales, because I don't know, whether there are empty ones in the production system

**Comment by fosterfarrell9** [comment]
That makes sense. I just looked into the production db. Currently there are no users with missing or incorrect locales.
