### ISSUE TITLE
Rationale for ajaxing lectures/new etc.

### ISSUE THREAD

**Issue by henrixapp** [fosterfarrell9/mampf#79]
When creating a simple lecture creation test, cypress warns 

```
This element <input.btn.btn-primary> is not visible because its parent <div#new-course-area.bg-green-lighten-4.p-3.mb-3.rounded> has CSS property: display: none

Fix this problem, or use {force: true} to disable error checking
```
, when trying to click on the "save lecture" button, after selecting the plus button.

When forcing to click, it kind of works, but no result/creation is displayed afterwards.

I can not tell, whether this issue is caused by cypress, because the hot plugged elements are displayed in their preview at some point.

I believe, that loading code and executing it as a "side-effect" causes this problem
I think the initial reason to load it via ajax was to automatically load the modules. Maybe migrating to an API approach, where fetching data, not code, could resolve this.

**Comment by henrixapp** [comment]
The problem is caused by the redirect after submission via Turbolinks (not a classical HTTP 302). still investigating whether it is a problem with cypress.

**Comment by fosterfarrell9** [comment]
Rationale is [this](https://signalvnoise.com/posts/3697-server-generated-javascript-responses) by DHH himself.

**Comment by henrixapp** [comment]
ok thanks. tried to click the wrong (course) save button 🤦, which  has the same content/meta, is hidden, and therefore couldn't be clicked. Shouldn't be the course creation be side loaded the same way?

**Comment by fosterfarrell9** [comment]
Hm, it seems indeed that the courses/_new partial is already rendered on the page, but hidden. I do not remember why there is this difference.
